+define+SYNTHESIS
+define+RVFI
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_dv_dv_macros_0
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_prim_assert_0.1/rtl
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_sonata_system_0/dv/verilator
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_prim_util_memload_0/rtl
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_dv_dv_fcov_macros_0
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_dv_dpi_c_uartdpi_0.1
-CFLAGS -I./build/lowrisc_sonata_system_0/src/lowrisc_dv_dpi_c_uartdpi_0.1

/tools/Xilinx/Vivado/2023.2/data/verilog/src/glbl.v
-f /tools/Xilinx/Vivado/2023.2/data/secureip/iserdese2/iserdese2_cell.list.f
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/ODDR.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/OBUF.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/IOBUF.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/IDELAYE2.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/ISERDESE2.v
/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
./build/lowrisc_sonata_system_0/src/lowrisc_constants_top_pkg_0/rtl/top_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_dv_pins_if_0/pins_if.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_pkg_0.1/rtl/ibex_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_pkg_0.1/rtl/cheri_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_pkg_0.1/rtl/i2c_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_pkg_0.1/rtl/usbdev_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_prim_pkg_0.1/prim_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_ram_1p_pkg_0/rtl/prim_ram_1p_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_ram_2p_pkg_0/rtl/prim_ram_2p_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_cipher_pkg_0.1/rtl/prim_cipher_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_and2_0/rtl/prim_generic_and2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_buf_0/rtl/prim_generic_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_clock_gating_0/rtl/prim_generic_clock_gating.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_flop_0/rtl/prim_generic_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_xnor2_0/rtl/prim_generic_xnor2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_xor2_0/rtl/prim_generic_xor2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_pad_wrapper_pkg_0/rtl/prim_pad_wrapper_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_28_22_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_28_22_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_64_57_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_64_57_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_76_68_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_76_68_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_64_57_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_64_57_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_76_68_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_76_68_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sha2_pkg_0/rtl/prim_sha2_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_and2_0/rtl/prim_xilinx_and2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_buf_0/rtl/prim_xilinx_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_clock_gating_0/rtl/prim_xilinx_clock_gating.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_clock_mux2_0/rtl/prim_xilinx_clock_mux2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_flop_0/rtl/prim_xilinx_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_flop_en_0/rtl/prim_xilinx_flop_en.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_xor2_0/rtl/prim_xilinx_xor2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_icache_0.1/rtl/ibex_icache.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_tracer_0.1/rtl/ibex_tracer_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_tracer_0.1/rtl/ibex_tracer.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_and2_0/prim_and2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_buf_0/prim_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_clock_gating_0/prim_clock_gating.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_flop_0/prim_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_xnor2_0/prim_xnor2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_xor2_0/prim_xor2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_fixed.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_ppc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_tree.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_arbiter_0/rtl/prim_arbiter_tree_dup.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_cdc_rand_delay_0/rtl/prim_cdc_rand_delay.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_cipher_0/rtl/prim_subst_perm.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_cipher_0/rtl/prim_present.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_cipher_0/rtl/prim_prince.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_count_0/rtl/prim_count.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_clock_mux2_0/rtl/prim_generic_clock_mux2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_pad_wrapper_0/rtl/prim_generic_pad_wrapper.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_ram_1p_0/rtl/prim_generic_ram_1p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_ram_2p_0/rtl/prim_generic_ram_2p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_lfsr_0.1/rtl/prim_lfsr.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_max_tree_0/rtl/prim_max_tree.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sec_anchor_0.1/rtl/prim_sec_anchor_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sec_anchor_0.1/rtl/prim_sec_anchor_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sha2_0/rtl/prim_sha2_pad.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sha2_0/rtl/prim_sha2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sha2_0/rtl/prim_sha2_32.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_util_0.1/rtl/prim_util_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_pad_wrapper_0/rtl/prim_xilinx_pad_wrapper.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_clock_mux2_0/prim_clock_mux2.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_pad_wrapper_0/prim_pad_wrapper.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_ram_2p_0/prim_ram_2p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_badbit_ram_1p_0/prim_badbit_ram_1p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_flop_en_0/rtl/prim_generic_flop_en.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_onehot_check_0/rtl/prim_onehot_check.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/cheri_decoder.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/cheri_ex.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/cheri_tbre.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/cheri_stkz.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/cheri_tbre_wrapper.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/cheri_trvk_stage.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_alu.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_branch_predict.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_compressed_decoder.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_controller.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_cs_registers.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_csr.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_counter.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_decoder.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_ex_block.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_fetch_fifo.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_id_stage.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_if_stage.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_load_store_unit.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_multdiv_fast.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_multdiv_slow.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_prefetch_buffer.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_pmp.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_wb_stage.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_dummy_instr.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_core_0.1/rtl/ibex_core.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_flop_en_0/prim_flop_en.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_ram_1p_0/prim_ram_1p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_flop_2sync_0/rtl/prim_flop_2sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi20_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi20_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi20_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi24_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi24_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi24_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi28_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi28_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi28_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi32_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi32_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_reg_we_check_0/rtl/prim_reg_we_check.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_rv_plic_component_0.1/rtl/rv_plic_gateway.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_rv_plic_component_0.1/rtl/rv_plic_target.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_diff_decode_0/rtl/prim_diff_decode.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_edge_detector_0.1/rtl/prim_edge_detector.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_fifo_0/rtl/prim_fifo_async_sram_adapter.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_fifo_0/rtl/prim_fifo_async_simple.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_fifo_0/rtl/prim_fifo_async.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_fifo_0/rtl/prim_fifo_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_fifo_0/rtl/prim_fifo_sync_cnt.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_clock_inv_0/rtl/prim_generic_clock_inv.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_rst_sync_0/rtl/prim_rst_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_subreg_0/rtl/prim_subreg_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_subreg_0/rtl/prim_reg_cdc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_subreg_0/rtl/prim_reg_cdc_arb.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_subreg_0/rtl/prim_subreg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_subreg_0/rtl/prim_subreg_arb.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_subreg_0/rtl/prim_subreg_ext.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_subreg_0/rtl/prim_subreg_shadow.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_headers_0.1/rtl/tlul_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_sim_shared_0/./rtl/ram_1p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_sim_shared_0/./rtl/ram_2p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_sim_shared_0/./rtl/bus.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_sim_shared_0/./rtl/timer.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_clock_inv_0/prim_clock_inv.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_esc_0/rtl/prim_esc_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_esc_0/rtl/prim_esc_receiver.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_esc_0/rtl/prim_esc_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_ram_1p_adv_0.1/rtl/prim_ram_1p_adv.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_data_integ_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_data_integ_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_cmd_intg_gen.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_cmd_intg_chk.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_rsp_intg_gen.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_trans_intg_0.1/rtl/tlul_rsp_intg_chk.sv
./vendor/ovgn/OpenHBMC/hdl/OpenHBMC.sv
./vendor/ovgn/OpenHBMC/hdl/hbmc_ufifo.sv
./vendor/ovgn/OpenHBMC/hdl/hbmc_iobuf.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_elastic_buf.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_dru.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_dfifo.sv
./vendor/ovgn/OpenHBMC/hdl/hbmc_ctrl.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_clk_obuf.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_bus_sync.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_bit_sync.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_arst_sync.v
./rtl/ip/hyperram/rtl/hbmc_tl_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_ram_1p_scr_0.1/rtl/prim_ram_1p_scr.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_common_0.1/rtl/tlul_fifo_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_common_0.1/rtl/tlul_fifo_async.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_common_0.1/rtl/tlul_assert.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_common_0.1/rtl/tlul_err.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_common_0.1/rtl/tlul_assert_multiple.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_ff.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_fpga.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_register_file_latch.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_top_0.1/rtl/cheri_regfile.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_top_0.1/rtl/ibex_lockstep.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_top_0.1/rtl/ibexc_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_clock_gating_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_sram_arbiter.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_slicer.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_sync_reqack.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_sync_reqack_data.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_sync_slow_fast.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_keccak.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_packer.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_packer_fifo.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_gate_gen.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_pulse_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_filter.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_filter_ctr.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_all_0.1/rtl/prim_intr_hw.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_adapter_host_0.1/rtl/tlul_adapter_host.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_adapter_reg_0.1/rtl/tlul_adapter_reg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_adapter_sram_0.1/rtl/tlul_sram_byte.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_adapter_sram_0.1/rtl/tlul_adapter_sram.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_socket_1n_0.1/rtl/tlul_err_resp.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_socket_1n_0.1/rtl/tlul_socket_1n.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_socket_m1_0.1/rtl/tlul_socket_m1.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_sram2tlul_0.1/rtl/sram2tlul.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ibex_ibex_top_tracing_0.1/rtl/ibexc_top_tracing.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_rgbled_ctrl_0.1/rtl/rgbled_ctrl_reg_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_rgbled_ctrl_0.1/rtl/rgbled_ctrl_reg_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_rgbled_ctrl_0.1/rtl/ws281x_drv.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_rgbled_ctrl_0.1/rtl/rgbled_ctrl.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_spi_0.1/rtl/spi_reg_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_spi_0.1/rtl/spi_reg_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_spi_0.1/rtl/spi_core.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_spi_0.1/rtl/spi.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_consts_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_nb_in_pe.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_nb_out_pe.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_nb_pe.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_rx.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_tx.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usb_fs_nb_pe_0.1/rtl/usb_fs_tx_mux.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/debug_rom/debug_rom.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/debug_rom/debug_rom_one_scratch.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/src/dm_pkg.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/src/dm_sba.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/src/dm_csrs.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/src/dm_mem.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/src/dmi_cdc.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/src/dmi_jtag.sv
./build/lowrisc_sonata_system_0/src/pulp_riscv_debug_module_0/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_0.1/rtl/i2c_reg_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_0.1/rtl/i2c_reg_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_0.1/rtl/i2c_fifo_sync_sram_adapter.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_0.1/rtl/i2c_fifos.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_0.1/rtl/i2c_core.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_0.1/rtl/i2c_fsm.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_i2c_0.1/rtl/i2c.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_uart_0.1/rtl/uart_reg_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_uart_0.1/rtl/uart_reg_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_uart_0.1/rtl/uart_rx.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_uart_0.1/rtl/uart_tx.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_uart_0.1/rtl/uart_core.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_uart_0.1/rtl/uart.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev_reg_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev_reg_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev_usbif.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev_linkstate.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev_iomux.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev_counter.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev_aon_wake.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_usbdev_0.1/rtl/usbdev.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_xbar_main_0.1/tl_main_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_xbar_main_0.1/xbar_main.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_xbar_ifetch_0.1/tl_ifetch_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_ip_xbar_ifetch_0.1/xbar_ifetch.sv
./build/lowrisc_sonata_system_0/src/lowrisc_opentitan_top_earlgrey_rv_plic_0/rtl/rv_plic_reg_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_opentitan_top_earlgrey_rv_plic_0/rtl/rv_plic_reg_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_opentitan_top_earlgrey_rv_plic_0/rtl/rv_plic.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/jtag_id_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/sonata_system.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/dm_top.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/debounce.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/gpio.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/pwm.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/pwm_wrapper.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/pwm_fade.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/sram.sv
./build/lowrisc_sonata_system_0/src/lowrisc_sonata_design_0/rtl/system/rv_timer.sv
./build/lowrisc_sonata_system_0/src/lowrisc_dv_dpi_sv_uartdpi_0.1/uartdpi.sv
./build/lowrisc_sonata_system_0/src/lowrisc_dv_dpi_c_uartdpi_0.1/uartdpi.c
./dv/xlm/top_tb.sv

./dv/hyperram-bfm/s27kl0642.v

