+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_dv_dv_macros_0
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_prim_util_memload_0/rtl
+incdir+./build/lowrisc_sonata_system_0/src/lowrisc_prim_assert_0.1/rtl
+incdir+./dv/hyperram-bfm/

/tools/Xilinx/Vivado/2023.2/data/verilog/src/glbl.v
-f /tools/Xilinx/Vivado/2023.2/data/secureip/iserdese2/iserdese2_cell.list.f
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/ODDR.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/OBUF.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/IOBUF.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/IDELAYE2.v
/tools/Xilinx/Vivado/2023.2/data/verilog/src/unisims/ISERDESE2.v
/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
/tools/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
./build/lowrisc_sonata_system_0/src/lowrisc_constants_top_pkg_0/rtl/top_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_prim_pkg_0.1/prim_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_buf_0/rtl/prim_generic_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_flop_0/rtl/prim_generic_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_28_22_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_28_22_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_64_57_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_64_57_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_76_68_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_hamming_76_68_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_28_22_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_64_57_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_64_57_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_22_16_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_39_32_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_72_64_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_72_64_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_76_68_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_secded_0.1/rtl/prim_secded_inv_hamming_76_68_enc.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_buf_0/rtl/prim_xilinx_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_xilinx_flop_0/rtl/prim_xilinx_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_buf_0/prim_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_flop_0/prim_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_cdc_rand_delay_0/rtl/prim_cdc_rand_delay.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sec_anchor_0.1/rtl/prim_sec_anchor_buf.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_sec_anchor_0.1/rtl/prim_sec_anchor_flop.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_util_0.1/rtl/prim_util_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_flop_2sync_0/rtl/prim_flop_2sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi4_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi8_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi12_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_sender.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_mubi_0.1/rtl/prim_mubi16_dec.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_diff_decode_0/rtl/prim_diff_decode.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_ram_1p_pkg_0/rtl/prim_ram_1p_pkg.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_generic_ram_1p_0/rtl/prim_generic_ram_1p.sv
./build/lowrisc_sonata_system_0/src/lowrisc_prim_abstract_ram_1p_0/prim_ram_1p.sv
./vendor/lowrisc_ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_fifo_sync_cnt.sv
./vendor/lowrisc_ibex/vendor/lowrisc_ip/ip/prim/rtl/prim_fifo_sync.sv
./build/lowrisc_sonata_system_0/src/lowrisc_tlul_headers_0.1/rtl/tlul_pkg.sv
./rtl/ip/hyperram/rtl/hbmc_tl_top.sv
./vendor/ovgn/OpenHBMC/hdl/OpenHBMC.sv
./vendor/ovgn/OpenHBMC/hdl/hbmc_ufifo.sv
./vendor/ovgn/OpenHBMC/hdl/hbmc_iobuf.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_elastic_buf.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_dru.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_dfifo.sv
./vendor/ovgn/OpenHBMC/hdl/hbmc_ctrl.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_clk_obuf.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_bus_sync.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_bit_sync.v
./vendor/ovgn/OpenHBMC/hdl/hbmc_arst_sync.v
./dv/hyperram-bfm/s27kl0642.v
./rtl/ip/hyperram/dv/hyperram_full_tb.sv
